### ISSUE TITLE
How to use this coco-minitrain?

### ISSUE THREAD

**Issue by andirahmadiansah** [giddyyupp/coco-minitrain#6]
Hi...
How to use this coco-minitrain?

I want to get APsmall, APmedium, APlarge? 
I confuse no example code.

Thank's alot

**Comment by giddyyupp** [comment]
Hi,

This coco-minitrain dataset is meant to use for training, not evaluation. You should use regular coco evaluation code (https://github.com/cocodataset/cocoapi).

The only thing you should change is json file name. Instead of passing regular coco train json file, you pass minitrain json. That's all :)
